drop table IF EXISTS Person cascade;
drop table IF EXISTS Tasks cascade;

CREATE TABLE IF NOT EXISTS Person (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email varchar(200) not null,
    form_password varchar(200) not null,
    username varchar(50),
    create_dt TIMESTAMP WITHOUT TIME ZONE not null,
    CONSTRAINT pk_person PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS Tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    person_id bigint NOT NULL,
    description varchar(1500) not null,
    category SMALLINT not null,
    is_done boolean not null,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    importance_level int,
    CONSTRAINT pk_tasks PRIMARY KEY (id),
    CONSTRAINT fk_tasks_person FOREIGN KEY (person_id) REFERENCES Person
);

INSERT into Person (email, form_password, create_dt) VALUES ('b9955047856@gmail.com', 'hellcherry', current_timestamp);



